name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        java-versions: ['11', '17', '21']
    name: Java ${{ matrix.java-versions }} Test on ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Set up JDK ${{ matrix.java-versions }}
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-versions }}
        cache: 'maven'

    - name: Run test suite
      run: mvn test
